# This file was generated by GoReleaser. DO NOT EDIT.
cask "figma-kai" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fa8584cbeac3973c15152aaeb9dd5ccbff4c5e1b1f9d247de11e4a111f04d7a7"
      url "https://github.com/Kaidstor/figma-kai/releases/download/v#{version}/figma-kai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f60a8b55a95bcc49b9b9ea27dcb2d9fb5a545a404f3e5be1c47f910875ccc78"
      url "https://github.com/Kaidstor/figma-kai/releases/download/v#{version}/figma-kai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac7db2a90dc1104d8621266f8678a9c78612c9bc8893609dac4e303283683124"
      url "https://github.com/Kaidstor/figma-kai/releases/download/v#{version}/figma-kai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2da9d47df2034869d633929a8292042abbba1496f3aa6ecb5b2c55a4ea807004"
      url "https://github.com/Kaidstor/figma-kai/releases/download/v#{version}/figma-kai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "figma-kai"
  desc "Макеты Figma из терминала: PNG экрана по ссылке и дерево слоёв с размерами, цветами и текстом"
  homepage "https://github.com/Kaidstor/figma-kai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "figma-kai"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/figma-kai"]
    end
  end

  # No zap stanza required
end
