# This file was generated by GoReleaser. DO NOT EDIT.
cask "finances-kai" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ce07de6546f3891e488b52fd483a27d55d9f79c4951894a500350b292e6f53bf"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc16f4f545711d9ced8ad6d796061f891a6eb86578b62207a0649d0b029a51e2"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ebc8b506f3468a8bd5cc3649bd29a463dd692f1feb2a0b222d8149cb040d001"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "355fbf4343fc9fa04ddf14af7f513b89ef522a72340fdcafc8f93e91c288e43a"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "finances-kai"
  desc "CLI для учёта доходов и расходов: платежи, шаблоны, чеки, сводка и экспорт счетов из терминала"
  homepage "https://github.com/Kaidstor/finances-kai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finances-kai"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finances-kai"]
    end
  end

  # No zap stanza required

end
