# This file was generated by GoReleaser. DO NOT EDIT.
cask "finances-kai" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1a2fe05118453d4a5669273c89d200aa31b0455418ca99a8887f254d44478e1e"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0f3607eea60d98bae79a0b8d5984648f3df1845257658de433510042b4f3df9"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06609fc97fbead61bcbdcba879cdf552cf5238f752eba16e68dc56c09474f208"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a113963203e948d032e086a302341aae9323ed9c2dd38e25580c43995d153eb"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "finances-kai"
  desc "CLI для учёта доходов и расходов: платежи, шаблоны, чеки, сводка и экспорт счетов из терминала"
  homepage "https://github.com/Kaidstor/finances-kai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finances-kai"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finances-kai"]
    end
  end

  # No zap stanza required

end
