# This file was generated by GoReleaser. DO NOT EDIT.
cask "finances-kai" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "396977dd10142fff3d25a3b429e3eb636d070a6b366de6167f3b42312a203568"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e16f81ebff0343d1487c20b685d7357ccf997438a06326d2be497a4d8b93b861"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "adbaf14ad54542cf45cb1055e88be2ded91bf3721e9a2bcff042334fb1581cee"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e00560918ec1c2e3e3ecbc7997b54e863c6ff414efcac46eaf22b19281f85f8"
      url "https://github.com/Kaidstor/finances-kai/releases/download/v#{version}/finances-kai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "finances-kai"
  desc "CLI для учёта доходов и расходов: платежи, шаблоны, чеки, сводка и экспорт счетов из терминала"
  homepage "https://github.com/Kaidstor/finances-kai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "finances-kai"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/finances-kai"]
    end
  end

  # No zap stanza required
end
