# This file was generated by GoReleaser. DO NOT EDIT.
cask "sec" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "f7fc91d4fd784b923d06c84c38b2c11e6d3245be652a7bdb0e9e1a4aca9c560a"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a99d0a2ba0b1e5250cb6583e2023c9ce29d6b390d27dc8689dec4f85b0bd6bc9"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8925f32a8c8a5e423fef333e744a094e0dcf8964a70b15118afb02587dd5a76d"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37cc509207823334eae2adc5d418dc47506e5d2bcd396ed578ff7b2bf88dbeee"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sec"
  desc "Локальный менеджер секретов для безопасной работы с агентами (значения не попадают в argv/историю/чат)"
  homepage "https://github.com/kaidstor/sec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sec"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sec"]
    end
  end

  postflight do
    if OS.mac?
      system_command "#{staged_path}/sec", args: ["skills", "install"], must_succeed: false
    end
  end
  generate_completions_from_executable "sec",
    base_name: "sec",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
