# This file was generated by GoReleaser. DO NOT EDIT.
cask "sec" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "4d10001c3bdd57f455a7b33597ee775720a12d2989cf523c76c759af51219a4e"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "18b1b95b2f0427d5a54e986381eda1068a8d6ca2be74ded1dc4a7460cb94cfe8"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e4a9b532ed5ba78c02c154ed915a70d9d1a353de352947ec009598d0f56a1fe"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35d85cadd800ad160e2af501b4b4a28aa76c80a93441c3d594de79f90a945ec2"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sec"
  desc "Локальный менеджер секретов для безопасной работы с агентами (значения не попадают в argv/историю/чат)"
  homepage "https://github.com/kaidstor/sec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sec"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sec"]
    end
  end

  postflight do
    if OS.mac?
      system_command "#{staged_path}/sec", args: ["skills", "install"], must_succeed: false
    end
  end
  generate_completions_from_executable "sec",
    base_name: "sec",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
