# This file was generated by GoReleaser. DO NOT EDIT.
cask "sec" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "fef44b66e2fa81d3a83fe32c32e493902eb42f7e10af9335c1e0841869eaca4d"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d8d2ec795fa4ef2b8ceff4c5f6b2a7fc7f1b359a52b1832faea20852904dfd3"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a65dc937cbd53cbbeb5788b921566a53cb9b60036e3d30fe926eafb41407e4d4"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1801f30f9d6d87ae0ce2c3bb1f624eb4bdbc14d3cbc2ff4223261958990c5249"
      url "https://github.com/Kaidstor/sec/releases/download/v#{version}/sec_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sec"
  desc "Локальный менеджер секретов для безопасной работы с агентами (значения не попадают в argv/историю/чат)"
  homepage "https://github.com/kaidstor/sec"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sec"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sec"]
    end
  end
  generate_completions_from_executable "sec", "completion",
    base_name: "sec",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
