# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sec < Formula
  desc "Локальный менеджер секретов для безопасной работы с агентами (значения не попадают в argv/историю/чат)"
  homepage "https://github.com/kaidstor/sec"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kaidstor/sec/releases/download/v0.1.0/sec_0.1.0_darwin_amd64.tar.gz"
      sha256 "9a95848255117bf9949ac89b7e22d87abdf53029b24926b21a602e333df87cb8"

      define_method(:install) do
        bin.install "sec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kaidstor/sec/releases/download/v0.1.0/sec_0.1.0_darwin_arm64.tar.gz"
      sha256 "00d2ea616c6bd59ea51405f8044795ec716445568b8fdcf9a45d106b52623dc1"

      define_method(:install) do
        bin.install "sec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kaidstor/sec/releases/download/v0.1.0/sec_0.1.0_linux_amd64.tar.gz"
      sha256 "77fea21fa7e3007b7ab5f37e488a1835a8f1f548102195af1e04f62ad2be5800"
      define_method(:install) do
        bin.install "sec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kaidstor/sec/releases/download/v0.1.0/sec_0.1.0_linux_arm64.tar.gz"
      sha256 "be863041d8385d35d7f9dce30f4645a837cb5cf03f28d550a5ee38ed52bd159c"
      define_method(:install) do
        bin.install "sec"
      end
    end
  end

  test do
    system "#{bin}/sec", "version"
  end
end
